export const HandymenServices = {
    "mainTitle": "Find Trusted Handymen Services Nearby",
    "subtitle" : "Reviewed and dependable handymen are just a few clicks away.",
    "hireTextTitle": "Handymen experts for hire",
    "hireTextDescription": [
		"You may come across tasks around your home that are far from being a DIY thing. You either lack practical skills or the right equipment to complete them. That’s when you need an expert handyman. And you can find one on taskMafia!",
		"Using our online platform, you can avail all kinds of handyman services, from a one-off job like an appliance installation to a multi-step assignment such as remodelling entire home. So whether it’s a work related to doors and windows, repair, maintenance, gardening, roofing or any big or small odd jobs, our handymen have all the right skills and tools to perform the task. You’ll only have to let them know the job in detail.",
		"Additionally, our badging system helps you verify that they are qualified and licensed to carry out the job you’re considering them for. So you’re at peace that you’ve hired someone who knows what he’s doing. And yes, you can always rest assured with your payment secure with taskMafia.",
		"So if you have any such to-d0 work, post your exact requirements with us and offer a fair price, and you’ll soon start receiving offers from the local specialists. Hire who fits the bill."
    ],
	"subCategoriesTitle": "Handyman Services",
	"subCategories": [
		"Acrylic Bath Repair",
		"Air Conditioning Repair",
		"Antenna Repair",
		"BBQ Repair",
		"Bed Repairs",
		"Bidet Seat Installation",
		"Blind Repairs & Installation",
		"Blueboard Installation",
		"Broken Sink Repair And Replacement",
		"Cafe Blinds Installation & Repair",
		"Carpet Repair",
		"Carpet Restoration And Repair",
		"Cat Door Installation",
		"Ceiling Fan Repair",
		"Cement Sheeting Installation",
		"Clothesline Installation & Repair",
		"Coffee Table Repair",
		"Cooktop Repair",
		"Cornice Repair",
		"Curtain Repair",
		"Curtain Rod Installation",
		"Custom Mailboxes",
		"Dining Chair Repair",
		"Dog Door Installation",
		"Dog House Builder",
		"Door Frame Installation",
		"Door Installation",
		"Door Repair",
		"Fireplace Installation & Repair",
		"Fitness Equipment Installation",
		"Flyscreen Installation & Repair",
		"Freezer Repair",
		"Furniture Repair",
		"Garage Door Installation",
		"Garden Shed Installation & Repair",
		"Gate Repair",
		"General Labour",
		"General Maintenance",
		"Glass Repair And Replacement",
		"Heat Pump Installation & Repair",
		"Home Maintenance",
		"Indoor Clothes Line Hanging",
		"Internal Door Installation",
		"Jack of all Trades",
		"Kitchen Cupboard Repair",
		"Kitchen Drawer Repair",
		"Kitchen Sink Installation & Repair",
		"Knife Sharpening",
		"Ladder Installation",
		"Laundry Tub Installation",
		"Lawn Mower Repair",
		"Lounge Repair",
		"Mailbox Installation & Repair",
		"Mirror Hanging",
		"Mirror Repair",
		"Office Chair Repair",
		"Outdoor Blinds Installation & Repair",
		"Outdoor Furniture Repair",
		"Patio Installation",
		"Pet Door Installation",
		"Picture Hanging And Art Installation",
		"Pool Filter Repair And Installation",
		"Pool Leak Repair",
		"Pool Table Repair",
		"Rangehood Repairs",
		"Recliner Repair",
		"Roller Shutter Repair & Installation",
		"Screen Door Hinge Repairs",
		"Shelf Hanging",
		"Shower Screen Installation & Repair",
		"Sink Installation & Repair",
		"Sliding Door Repair",
		"Sofa Bed Repairs",
		"Soundproofing",
		"Spa Repair",
		"Split System Repairs",
		"Stove Repairs",
		"Table Lamp Repair",
		"Toilet Repair",
		"Toilet Hand Held Spray Installation",
		"Trampoline Repair",
		"Venetian Blind Repair & Installation",
		"Video Game Repairs",
		"Wall Mounting",
		"Wardrobe Repair",
		"Water Tank Installation & Repair",
		"Waterproofing",
		"Weatherboard Repair",
		"Window Frame Repair",
		"Window Installation & Repair",
		"Welding Repairs",
		"Window Frame Installation And Repair"
	],
    "recentTask": [
        {
            "imageUrl": 'https://abc.jpg',
            "jobTitle": 'Fit Audio Head Unit and Reverse Camera',
            "budget": '50',
            "countryCode": 'NZ',
            "datePosted": '16-07-2018',
            "detailDescription": "Mitsubishi Triton - Remove factory stereo unit and replace with new Audio Unit and also install a reverse camera.",
            "location": 'test_location',
            "ratings": 4.5,
            "reviewCommnets":[
                'Thanks for a great job George. Went above and beyond and did more than what I asked for! Lovely family too. Would definitely recommend. '
            ]
        },
        {
            "imageUrl": 'https://abc.jpg',
            "jobTitle": 'Fit Audio Head Unit and Reverse Camera',
            "budget": '50',
            "countryCode": 'NZ',
            "datePosted": '16-07-2018',
            "detailDescription": "Mitsubishi Triton - Remove factory stereo unit and replace with new Audio Unit and also install a reverse camera.",
            "location": 'test_location',
            "ratings": 4.5,
            "reviewCommnets":[
                'Thanks for a great job George. Went above and beyond and did more than what I asked for! Lovely family too. Would definitely recommend. '
            ]
        },
        {
            "imageUrl": 'https://abc.jpg',
            "jobTitle": 'Fit Audio Head Unit and Reverse Camera',
            "budget": '50',
            "countryCode": 'NZ',
            "datePosted": '16-07-2018',
            "detailDescription": "Mitsubishi Triton - Remove factory stereo unit and replace with new Audio Unit and also install a reverse camera.",
            "location": 'test_location',
            "ratings": 4.5,
            "reviewCommnets":[
                'Thanks for a great job George. Went above and beyond and did more than what I asked for! Lovely family too. Would definitely recommend. '
            ]
        },{
            "imageUrl": 'https://abc.jpg',
            "jobTitle": 'Fit Audio Head Unit and Reverse Camera',
            "budget": '50',
            "countryCode": 'NZ',
            "datePosted": '16-07-2018',
            "detailDescription": "Mitsubishi Triton - Remove factory stereo unit and replace with new Audio Unit and also install a reverse camera.",
            "location": 'test_location',
            "ratings": 4.5,
            "reviewCommnets":[
                'Thanks for a great job George. Went above and beyond and did more than what I asked for! Lovely family too. Would definitely recommend. '
            ]
        },
        {
            "imageUrl": 'https://abc.jpg',
            "jobTitle": 'Fit Audio Head Unit and Reverse Camera',
            "budget": '50',
            "countryCode": 'NZ',
            "datePosted": '16-07-2018',
            "detailDescription": "Mitsubishi Triton - Remove factory stereo unit and replace with new Audio Unit and also install a reverse camera.",
            "location": 'test_location',
            "ratings": 4.5,
            "reviewCommnets":[
                'Thanks for a great job George. Went above and beyond and did more than what I asked for! Lovely family too. Would definitely recommend. '
            ]
        }


    ]
}